spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my_provider
            client-id: gateway-client
            client-secret: KSTJK49FyLp0WrDIXlUncyHfqc5ovmXK
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8088/login/oauth2/code/keycloak'
            scope:
              - openid
        provider:
          my_provider:
            issuer-uri: http://localhost:8080/realms/store-gateway


  cloud:
    gateway:
      default-filters:
        - TokenRelay=